### ISSUE TITLE
Fix syntax-operators to work with Freya 1.0.*

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya.examples#1]
@kolektiv I tried updating everything, but I can't seem to get the TodoBackend tests to work.

**Comment by kolektiv** [comment]
That's quite odd. I just checked the branch out, restored the packages and built it, and it works fine for me... What are the errors you're getting? More repro?

**Comment by panesofglass** [comment]
Oh, good! I couldn't get any of the TodoBackend tests to pass. If your copy works, I'll assume it was a caching issue on my end.
